name: Maven release publish to package registry

on:
  release:
    types: [ published ]
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Build and publish to GitHub Packages
      run: mvn deploy -s ${{ github.workspace }}/.m2/settings.xml -P release
